#!/bin/bash
# Interactive Terraform Setup for ELB DDoS Defender

set -e

echo "=========================================="
echo "  ELB DDoS Defender - Interactive Setup"
echo "=========================================="
echo ""

# Check if AWS CLI is configured
if ! aws sts get-caller-identity &>/dev/null; then
    echo "❌ AWS CLI not configured. Run 'aws configure' first."
    exit 1
fi

# Get region
echo "📍 Select AWS Region:"
echo "1) us-east-1 (N. Virginia)"
echo "2) us-west-2 (Oregon)"
echo "3) eu-west-1 (Ireland)"
echo "4) Custom region"
read -p "Enter choice [1-4]: " region_choice

case $region_choice in
    1) REGION="us-east-1" ;;
    2) REGION="us-west-2" ;;
    3) REGION="eu-west-1" ;;
    4) read -p "Enter region: " REGION ;;
    *) echo "Invalid choice"; exit 1 ;;
esac

echo "✅ Using region: $REGION"
echo ""

# List VPCs
echo "🌐 Available VPCs in $REGION:"
aws ec2 describe-vpcs --region $REGION \
    --query 'Vpcs[*].[VpcId,CidrBlock,Tags[?Key==`Name`].Value|[0],IsDefault]' \
    --output table

read -p "Enter VPC ID: " VPC_ID

# Validate VPC
if ! aws ec2 describe-vpcs --vpc-ids $VPC_ID --region $REGION &>/dev/null; then
    echo "❌ Invalid VPC ID"
    exit 1
fi

echo "✅ Using VPC: $VPC_ID"
echo ""

# List subnets in VPC
echo "📡 Available Subnets in $VPC_ID:"
aws ec2 describe-subnets --region $REGION \
    --filters "Name=vpc-id,Values=$VPC_ID" \
    --query 'Subnets[*].[SubnetId,CidrBlock,AvailabilityZone,MapPublicIpOnLaunch,Tags[?Key==`Name`].Value|[0]]' \
    --output table

read -p "Enter Subnet ID: " SUBNET_ID

# Validate subnet
if ! aws ec2 describe-subnets --subnet-ids $SUBNET_ID --region $REGION &>/dev/null; then
    echo "❌ Invalid Subnet ID"
    exit 1
fi

# Check if subnet is public or private
IS_PUBLIC=$(aws ec2 describe-subnets --subnet-ids $SUBNET_ID --region $REGION \
    --query 'Subnets[0].MapPublicIpOnLaunch' --output text)

echo "✅ Using Subnet: $SUBNET_ID ($([ "$IS_PUBLIC" = "True" ] && echo "Public" || echo "Private"))"
echo ""

# Access method
echo "🔐 Select Access Method:"
if [ "$IS_PUBLIC" = "True" ]; then
    echo "1) Session Manager (No SSH key needed)"
    echo "2) SSH (Requires key pair)"
    read -p "Enter choice [1-2]: " access_choice
    
    if [ "$access_choice" = "2" ]; then
        ENABLE_PUBLIC_IP="true"
        
        # List key pairs
        echo ""
        echo "🔑 Available Key Pairs in $REGION:"
        aws ec2 describe-key-pairs --region $REGION \
            --query 'KeyPairs[*].[KeyName,KeyPairId]' \
            --output table
        
        read -p "Enter Key Pair name (or leave empty for Session Manager): " KEY_NAME
        
        if [ -z "$KEY_NAME" ]; then
            ENABLE_PUBLIC_IP="false"
            KEY_NAME=""
        fi
    else
        ENABLE_PUBLIC_IP="false"
        KEY_NAME=""
    fi
else
    echo "ℹ️  Private subnet detected - using Session Manager only"
    ENABLE_PUBLIC_IP="false"
    KEY_NAME=""
fi

echo ""

# Email address
read -p "📧 Enter email address for alerts: " EMAIL_ADDRESS

# Validate email
if [[ ! "$EMAIL_ADDRESS" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
    echo "❌ Invalid email address"
    exit 1
fi

echo ""

# Instance type
echo "💻 Select Instance Type:"
echo "1) t3.medium (Recommended - Up to 5 ELBs)"
echo "2) t3.large (5-10 ELBs)"
echo "3) t3.xlarge (10+ ELBs)"
read -p "Enter choice [1-3]: " instance_choice

case $instance_choice in
    1) INSTANCE_TYPE="t3.medium" ;;
    2) INSTANCE_TYPE="t3.large" ;;
    3) INSTANCE_TYPE="t3.xlarge" ;;
    *) INSTANCE_TYPE="t3.medium" ;;
esac

echo "✅ Using instance type: $INSTANCE_TYPE"
echo ""

# Summary
echo "=========================================="
echo "  Configuration Summary"
echo "=========================================="
echo "Region:           $REGION"
echo "VPC:              $VPC_ID"
echo "Subnet:           $SUBNET_ID"
echo "Instance Type:    $INSTANCE_TYPE"
echo "Email:            $EMAIL_ADDRESS"
echo "Public IP:        $ENABLE_PUBLIC_IP"
echo "SSH Key:          ${KEY_NAME:-None (Session Manager)}"
echo "=========================================="
echo ""

read -p "Proceed with deployment? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo "❌ Deployment cancelled"
    exit 0
fi

# Create terraform.tfvars
cat > terraform.tfvars <<EOF
# Auto-generated by setup.sh

aws_region    = "$REGION"
vpc_id        = "$VPC_ID"
subnet_id     = "$SUBNET_ID"
email_address = "$EMAIL_ADDRESS"

instance_type      = "$INSTANCE_TYPE"
enable_public_ip   = $ENABLE_PUBLIC_IP
key_name           = "$KEY_NAME"
allowed_ssh_cidr   = "0.0.0.0/0"

tags = {
  Project     = "ELB-DDoS-Defender"
  Environment = "Production"
  ManagedBy   = "Terraform"
}
EOF

echo "✅ Created terraform.tfvars"
echo ""

# Initialize and apply
echo "🚀 Initializing Terraform..."
terraform init

echo ""
echo "📋 Planning deployment..."
terraform plan

echo ""
read -p "Apply this configuration? (yes/no): " apply_confirm

if [ "$apply_confirm" = "yes" ]; then
    echo ""
    echo "🚀 Deploying infrastructure..."
    terraform apply -auto-approve
    
    echo ""
    echo "=========================================="
    echo "  ✅ Deployment Complete!"
    echo "=========================================="
    echo ""
    
    INSTANCE_ID=$(terraform output -raw instance_id)
    
    if [ "$ENABLE_PUBLIC_IP" = "true" ] && [ -n "$KEY_NAME" ]; then
        PUBLIC_IP=$(terraform output -raw instance_public_ip)
        echo "🔗 SSH Access:"
        echo "   ssh -i $KEY_NAME.pem ec2-user@$PUBLIC_IP"
    else
        echo "🔗 Session Manager Access:"
        echo "   aws ssm start-session --target $INSTANCE_ID --region $REGION"
    fi
    
    echo ""
    echo "📊 View Dashboard:"
    echo "   sudo /opt/elb-ddos-defender/dashboard.sh"
    echo ""
    echo "📝 View Logs:"
    echo "   sudo tail -f /var/log/elb-ddos-defender/defender.log"
    echo ""
    echo "⏳ Installation will complete in ~5 minutes"
    echo "=========================================="
else
    echo "❌ Deployment cancelled"
fi
